version: '3.9'

services:
  snapcast_node:
    image: ghcr.io/shuricksumy/ledfx-snapcast-docker:latest
    container_name: snapcast_audio
    restart: always
    network_mode: host
    # chown -R 1000:1000 ${DATA_DIR}/snapserver/config once after upgrading
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    environment:
      - ROLE=snapserver
      - EXTRA_ARGS=-v # Enable verbose logging for the server
    volumes:
      - ${DATA_DIR}/snapserver/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /tmp/snapfifo:/tmp