[server]
datadir = /config/

[http]
enabled = true
doc_root = /usr/share/snapserver/snapweb
port = 1780

[tcp-control]
enabled = true
bind_to_address = 0.0.0.0
port = 1705

[stream]
# Default format for the server
sampleformat = 48000:16:2
codec = flac
# Allow clients to request different chunks to improve sync
chunk_ms = 20

# --- STREAMS ---
# 1. Main Music Stream (Renamed to 'default')
source = pipe:///tmp/snapfifo?name=default&sampleformat=48000:16:2

# 2. LedFx Dedicated Stream (Match LedFx native rate)
# We add &mode=read to ensure the pipe stays open even if no one is writing
source = pipe:///tmp/snapfifo_ledfx?name=LedFx_Source&sampleformat=44100:16:2

# 3. Optional: TCP stream if you want to send audio from another PC via CLI
# source = tcp://0.0.0.0:4953?name=Remote_Input