version: '3.9'
services:
  snapserver:
    image: dc8ca81f78b9
    container_name: snapserver
    environment:
      - ROLE=server
    #  - EXTRA_ARGS=
    volumes:
      - ${DATA_DIR}/snapcast:/tmp/snapcast
      - ${DATA_DIR}/snapserver/config:/config
    network_mode: host
    restart: unless-stopped