version: '3.9'

services:
  ledfx:
    image: your-snapcast-image:latest
    container_name: ledfx
    environment:
      - ROLE=ledfx
      - HOST=192.168.1.100  # Replace with your Snapserver IP
      - EXTRA_ARGS=--sound pulse --soundcard alsa_output.pci-0000_00_1b.0.analog-stereo.monitor --hostID LedFX
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    volumes:
      - ./ledfx:/root/.ledfx
      - $XDG_RUNTIME_DIR/pulse:/run/user/1000/pulse
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
      - /dev/snd:/dev/snd
    devices:
      - /dev/snd
    #network_mode: host
    ports:
      - "8889:8888" # ledfx web port
    restart: unless-stopped

    # 🔄 To use ALSA (ensure loopback is enabled):
    # environment:
    #   - ROLE=ledfx
    #   - HOST=192.168.1.100
    #   - EXTRA_ARGS=--sound alsa --soundcard Loopback --hostID LedFX