services: 
  snapclient-ledfx:
    image: ec4f754b684e
    container_name: snapclient-ledfx
    restart: unless-stopped
    deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 0
    ports:
      - "8888:8888" # ledfx web port
    environment:
      - HOST=192.168.88.111  # Static IP of Snapserver
      - ROLE=ledfx
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - EXTRA_ARGS="--hostID=MyClient --sound=pulse --soundcard=default"
      # Default EXTRA_ARGS is set as
      # - EXTRA_ARGS=--sound alsa --soundcard "Loopback" --hostID LedFX
    volumes:
      - ./ledfx:/root/.ledfx
      - /run/user/1000/pulse:/run/user/1000/pulse
    devices:
      - "/dev/snd:/dev/snd"  # Access to host audio devicess